CREATE EXTENSION IF NOT EXISTS azure_ai CASCADE;
CREATE EXTENSION IF NOT EXISTS vector CASCADE;
CREATE EXTENSION IF NOT EXISTS pg_diskann CASCADE;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS horizon_ship;

CREATE TABLE IF NOT EXISTS horizon_ship.shipments (
	id uuid PRIMARY KEY DEFAULT public.uuid_generate_v4(),
	shipment_number text NOT NULL UNIQUE,
	title text NOT NULL,
	description text NOT NULL,
	origin_name text NOT NULL,
	origin_position public.geometry(Point, 4326) NOT NULL,
	destination_name text NOT NULL,
	destination_position public.geometry(Point, 4326) NOT NULL,
	current_location_name text NOT NULL,
	current_position public.geometry(Point, 4326) NOT NULL,
	status text NOT NULL CHECK (
		status IN ('in_transit', 'delivered', 'delayed', 'exception', 'unknown')
	),
	eta date,
	updated_at timestamptz NOT NULL DEFAULT now(),
	embedding public.vector(1536),
	metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE horizon_ship.shipments
	ADD COLUMN IF NOT EXISTS embedding public.vector(1536);

CREATE INDEX IF NOT EXISTS shipments_current_position_gix
	ON horizon_ship.shipments USING gist (current_position);
CREATE INDEX IF NOT EXISTS shipments_status_idx
	ON horizon_ship.shipments (status);

COMMENT ON TABLE horizon_ship.shipments IS
	'Shipping data combining relational fields, PostGIS locations, and pgvector embeddings indexed by DiskANN.';
COMMENT ON COLUMN horizon_ship.shipments.embedding IS
	'text-embedding-3-small 1536-dimensional embedding generated by Azure OpenAI and searched with spherical-quantized DiskANN.';
